In [238]:
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
%run dataloader.ipynb

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')
(100837, 4)
[[1.00000e+00 1.00000e+00 4.00000e+00]
 [1.00000e+00 3.00000e+00 4.00000e+00]
 [1.00000e+00 6.00000e+00 4.00000e+00]
 ...
 [6.10000e+02 1.68250e+05 5.00000e+00]
 [6.10000e+02 1.68252e+05 5.00000e+00]
 [6.10000e+02 1.70875e+05 3.00000e+00]]
9742
9742
<class 'dict'>
(9742,)
201
(array([   0,    2,    5,   43,   46,   62,   89, 

In [239]:
Rat = final_ratings
rat_bool = np.array(final_ratings.T > 0)
nums = np.sum(rat_bool,axis = 1,keepdims=True)
print(nums.shape)
nums_tensor = torch.from_numpy(nums)
print("shape of rat_bool = ",rat_bool.shape)
rat_bool_tensor = torch.from_numpy(rat_bool)
print("shape of Rat = ",Rat.shape)
num_users = Rat.shape[0]
print("num_users =",num_users)
num_movies = Rat.shape[1]
num_features = 10
rat_tensor = torch.from_numpy(Rat.T)
print("rat_tensor shape = ",rat_tensor.shape)
rat_tensor_masked = torch.mul(rat_tensor,rat_bool_tensor)
print("rat_tensor_masked shape = ",rat_tensor_masked.shape)
print("sum shape = ",torch.sum(rat_tensor_masked,dim=1,keepdim=True).shape)
rat_tensor_mean = rat_tensor_masked - (torch.div( (torch.sum(rat_tensor_masked,dim=1,keepdim=True)) ,nums_tensor))
print(rat_tensor_mean)
X = torch.randn((num_movies,10),dtype=float,requires_grad = True)
theta = torch.randn((num_features,num_users),dtype=float,requires_grad=True)
preds = X @ theta

print(rat_bool_tensor.shape)
# diff = preds-rat_tensor
# print(diff.shape)
# diff_select = torch.masked_select(diff,rat_bool_tensor)
# mse_select = (torch.square(diff_select)).sum
# weight_decay = 1e-5
# regex = (torch.sum(torch.square(X)))*weight_decay
# regtheta = (torch.sum(torch.square(theta)))*weight_decay
# loss = (torch.square(torch.masked_select(rat_tensor_mean - (X @ theta),rat_bool_tensor))).sum() + regex + regtheta
# print(loss)
# loss.backward()
# print(X.grad)
# print(theta.grad)
# X = X - (1e-3) * X.grad
# theta = theta - (1e-3) * theta.grad
# print(type(theta))
# loss = (torch.square(torch.masked_select(rat_tensor_mean - (X @ theta),rat_bool_tensor))).sum() + regex + regtheta
# print(loss)

# X = torch.randn((6,4),dtype = float,requires_grad = True)
# theta = torch.randn((4,3),dtype =float, requires_grad = True)
# preds = X @ theta 
# loss_fn = F.mse_loss

# print(regex)
# loss = loss_fn((X @ theta), Rat) + regex + regtheta
# print("loss = ",loss) # use loss.item()
# print(X,"\n",theta)


(9742, 1)
shape of rat_bool =  (9742, 610)
shape of Rat =  (610, 9742)
num_users = 610
rat_tensor shape =  torch.Size([9742, 610])
rat_tensor_masked shape =  torch.Size([9742, 610])
sum shape =  torch.Size([9742, 1])
tensor([[ 0.0791, -3.9209, -3.9209,  ..., -1.4209, -0.9209,  1.0791],
        [-3.4318, -3.4318, -3.4318,  ..., -1.4318, -3.4318, -3.4318],
        [ 0.7404, -3.2596, -3.2596,  ..., -1.2596, -3.2596, -3.2596],
        ...,
        [-3.5000, -3.5000, -3.5000,  ..., -3.5000, -3.5000, -3.5000],
        [-3.5000, -3.5000, -3.5000,  ..., -3.5000, -3.5000, -3.5000],
        [-4.0000, -4.0000, -4.0000,  ..., -4.0000, -4.0000, -4.0000]],
       dtype=torch.float64)
torch.Size([9742, 610])


In [240]:

# # Rat = np.array([[4,5,6,7,8,9],[3,4,6,7,1,9],[2,5,6,8,9,10]],dtype=float).T
# Rat = torch.from_numpy(Rat)
# print(Rat) # 5,3
# X = torch.randn((6,4),dtype = float,requires_grad = True)
# theta = torch.randn((4,3),dtype =float, requires_grad = True)
# preds = X @ theta 
# loss_fn = F.mse_loss
# weight_decay = 1e-5
# regex = (torch.sum(torch.square(X)))*weight_decay
# regtheta = (torch.sum(torch.square(theta)))*weight_decay
# print(regex)
# loss = loss_fn((X @ theta), Rat) + regex + regtheta
# print("loss = ",loss) # use loss.item()
# print(X,"\n",theta)


In [241]:

train_ds = TensorDataset(rat_tensor_mean)
print(train_ds.tensors)
train_dl = DataLoader(train_ds,shuffle = False)
for rat in train_dl: 
    print(rat)
    break

(tensor([[ 0.0791, -3.9209, -3.9209,  ..., -1.4209, -0.9209,  1.0791],
        [-3.4318, -3.4318, -3.4318,  ..., -1.4318, -3.4318, -3.4318],
        [ 0.7404, -3.2596, -3.2596,  ..., -1.2596, -3.2596, -3.2596],
        ...,
        [-3.5000, -3.5000, -3.5000,  ..., -3.5000, -3.5000, -3.5000],
        [-3.5000, -3.5000, -3.5000,  ..., -3.5000, -3.5000, -3.5000],
        [-4.0000, -4.0000, -4.0000,  ..., -4.0000, -4.0000, -4.0000]],
       dtype=torch.float64),)
[tensor([[ 0.0791, -3.9209, -3.9209, -3.9209,  0.0791, -3.9209,  0.5791, -3.9209,
         -3.9209, -3.9209, -3.9209, -3.9209, -3.9209, -3.9209, -1.4209, -3.9209,
          0.5791, -0.4209,  0.0791, -3.9209, -0.4209, -3.9209, -3.9209, -3.9209,
         -3.9209, -3.9209, -0.9209, -3.9209, -3.9209, -3.9209,  1.0791, -0.9209,
         -0.9209, -3.9209, -3.9209, -3.9209, -3.9209, -3.9209, -3.9209,  1.0791,
         -3.9209, -3.9209,  1.0791, -0.9209,  0.0791,  1.0791, -3.9209, -3.9209,
         -3.9209, -0.9209, -3.9209, -3.9209, -3.

In [242]:
def model(X,theta):
    return X @ theta


In [243]:
def loss_fn(preds,targets,X,theta):
    weight_decay = 1e-5
    regex = (torch.sum(torch.square(X)))*weight_decay
    regtheta = (torch.sum(torch.square(theta)))*weight_decay
    return  (torch.square(torch.masked_select(rat_tensor_mean - (X @ theta),rat_bool_tensor))).sum() + regex + regtheta
    

In [244]:
preds = model(X,theta)
print(loss_fn(preds,rat_tensor_mean,X,theta))
print(torch.sum(rat_tensor_mean,dim = 1))
loss = (loss_fn(preds,rat_tensor_mean,X,theta))
loss.backward()
print(X)

tensor(1049963.1244, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([-1548.7674, -1715.9091, -1818.8654,  ..., -2131.5000, -2131.5000,
        -2436.0000], dtype=torch.float64)
tensor([[-0.3885, -0.9913,  3.1413,  ...,  0.1907, -2.7712, -0.5394],
        [ 2.9572, -0.8047, -0.0039,  ..., -0.0868,  1.3606,  0.6509],
        [ 1.2241,  0.7639, -0.0064,  ..., -1.4547, -0.7896, -0.7220],
        ...,
        [-1.2248, -0.4652,  1.7068,  ...,  0.1482,  1.2827, -0.9495],
        [ 0.0319,  1.3526, -0.8578,  ...,  0.4516, -0.6249, -0.3000],
        [ 0.7485,  1.7176, -1.0088,  ..., -2.2162, -0.2102,  0.9666]],
       dtype=torch.float64, requires_grad=True)


In [245]:
epochs = 100

for i in range(100):
    # Iterate through training dataloader
    #print(X)
   
    # Generate Prediction
    preds = model(X,theta)
    loss = loss_fn(preds,rat_tensor_mean,X,theta)
    loss.backward()

    with torch.no_grad():
        X -= X.grad *1e-7
        theta -= theta.grad * 1e-7
        # Set the gradients to zero
        X.grad.zero_()
        theta.grad.zero_()

    print(f"Epoch {i}/{epochs}: Loss: {loss}")

Epoch 0/100: Loss: 1049963.1244317894
Epoch 1/100: Loss: 1049967.6270006846
Epoch 2/100: Loss: 1049969.8801740524
Epoch 3/100: Loss: 1049972.134426143
Epoch 4/100: Loss: 1049974.3897569631
Epoch 5/100: Loss: 1049976.6461665214
Epoch 6/100: Loss: 1049978.9036548256
Epoch 7/100: Loss: 1049981.162221883
Epoch 8/100: Loss: 1049983.4218677015
Epoch 9/100: Loss: 1049985.682592289
Epoch 10/100: Loss: 1049987.9443956534
Epoch 11/100: Loss: 1049990.2072778023
Epoch 12/100: Loss: 1049992.4712387433
Epoch 13/100: Loss: 1049994.7362784848
Epoch 14/100: Loss: 1049997.0023970343
Epoch 15/100: Loss: 1049999.2695943993
Epoch 16/100: Loss: 1050001.5378705878
Epoch 17/100: Loss: 1050003.8072256078
Epoch 18/100: Loss: 1050006.077659467
Epoch 19/100: Loss: 1050008.3491721738
Epoch 20/100: Loss: 1050010.6217637348
Epoch 21/100: Loss: 1050012.8954341586
Epoch 22/100: Loss: 1050015.1701834532
Epoch 23/100: Loss: 1050017.4460116262
Epoch 24/100: Loss: 1050019.7229186855
Epoch 25/100: Loss: 1050022.0009046388


In [246]:
# opt = torch.optim.SGD((X,theta), lr = 1e-3, weight_decay = 1e-5)
# opt.step()
# num_epochs = 100

In [247]:
# for epoch in range(num_epochs):
        
#         # Train with batches of data
#         for rat in train_dl:
            
#             # 1. Generate predictions
#             preds = X @ theta
            
#             # 2. Calculate loss
            

#             print(loss)
            
#             # 3. Compute gradients
#             loss.backward()
            
#             # 4. Update parameters using gradients
#             opt.step()
            
#             # 5. Reset the gradients to zero
#             opt.zero_grad()

In [248]:


# rat = Rat.clone().detach()
# print(rat)

In [249]:
# num_epochs = 10000
# learning_rate  = 1e-3
# for i in range (num_epochs):
#   preds = X @ theta
#   loss = (torch.square(torch.masked_select(rat_tensor_mean - (X @ theta),rat_bool_tensor))).sum() + regex + regtheta
#   loss.backward(retain_graph=True)
#   with torch.no_grad():
#     theta -= theta.grad*learning_rate
#     X -= X.grad*learning_rate
#     X.grad.zero_()
#     theta.grad.zero_()
#   #the variables in this system are X, theta and rat ( ratings ) 
  
# print(loss_fn((X @ theta),Rat), '\n')
# print("Predictions = \n", (X @ theta))
# print("Ratings =\n ",Rat)
# print(X)
# print(theta)



In [251]:

optimizer = torch.optim.SGD((X,theta), lr = 1e-7 , weight_decay = 1e-5)
for i in range (3):
  for r in train_dl:
    loss = loss_fn(X @ theta, rat_tensor_mean,X,theta)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    print(loss)



tensor(1050738.5493, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050741.1459, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050743.7436, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050746.3424, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050748.9422, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050751.5432, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050754.1452, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050756.7483, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050759.3525, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050761.9578, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050764.5641, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050767.1716, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050769.7801, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050772.3897, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1050775.0004, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(105

KeyboardInterrupt: 

In [ ]:
print(X @ theta)

tensor([[3.9998, 2.9998, 2.0002],
        [5.0002, 4.0003, 4.9995],
        [5.9998, 5.9998, 6.0002],
        [6.9997, 6.9996, 8.0004],
        [7.9999, 1.0000, 9.0000],
        [9.0002, 9.0003, 9.9996]], dtype=torch.float64, grad_fn=<MmBackward0>)


In [ ]:
print(Rat)

tensor([[ 4.,  3.,  2.],
        [ 5.,  4.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  8.],
        [ 8.,  1.,  9.],
        [ 9.,  9., 10.]], dtype=torch.float64)


In [ ]:
print(loss_fn((X @theta),Rat))

tensor(7.3555e-08, dtype=torch.float64, grad_fn=<MseLossBackward0>)


In [ ]:
print(Rat)
print(theta)

tensor([[ 4.,  3.,  2.],
        [ 5.,  4.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  8.],
        [ 8.,  1.,  9.],
        [ 9.,  9., 10.]], dtype=torch.float64)
tensor([[-1.3772, -1.2660,  0.6727],
        [ 2.9676,  1.6857,  3.2378],
        [-1.3171,  0.8915, -1.0399],
        [ 0.5296, -1.8645, -1.6353]], dtype=torch.float64, requires_grad=True)
