In [14]:
import pandas as pd
import numpy as np
from numpy import genfromtxt

dataset = pd.read_csv('/home/arkartik/engage_2022/dataset/ratings.csv')
print(dataset)
print(type(dataset))

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>


In [15]:
print((dataset.columns))

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')


In [16]:
ratings = np.genfromtxt('/home/arkartik/engage_2022/dataset/ratings.csv',delimiter=',', dtype=float)
print(ratings.shape)
ratings = ratings[np.arange(1,ratings.shape[0]),:]
ratings = ratings[:,[0,1,2]]
print(ratings)

(100837, 4)
[[1.00000e+00 1.00000e+00 4.00000e+00]
 [1.00000e+00 3.00000e+00 4.00000e+00]
 [1.00000e+00 6.00000e+00 4.00000e+00]
 ...
 [6.10000e+02 1.68250e+05 5.00000e+00]
 [6.10000e+02 1.68252e+05 5.00000e+00]
 [6.10000e+02 1.70875e+05 3.00000e+00]]


In [17]:
ratings[:,2]

array([4., 4., 4., ..., 5., 5., 3.])

In [18]:
links = np.genfromtxt('/home/arkartik/engage_2022/dataset/links.csv',delimiter = ',',dtype= int)
movie_ids = links[np.arange(1,links.shape[0]),0] 
list_of_movie_ids = list(movie_ids)
values_of_dictionary = list(np.arange(0,movie_ids.shape[0]))
print(len(values_of_dictionary))
print(len(list_of_movie_ids))
res = {list_of_movie_ids[i]: values_of_dictionary[i] for i in range(len(list_of_movie_ids))}
res_reverse = {values_of_dictionary[i]:list_of_movie_ids[i] for i in range(len(list_of_movie_ids))}
res[1]
print (type(res))
print(movie_ids.shape)

9742
9742
<class 'dict'>
(9742,)


In [19]:
final_ratings = np.zeros((611,movie_ids.shape[0]))
for row in ratings:
    user = int(row[0])
    movie_id = int(row[1])
    movie_key = res[movie_id]
    final_ratings[user][movie_key] = row[2]


In [20]:
print(res[235]) #the key for the movie id 3235
print (np.where(final_ratings[1] > 0)) #the 'values' for the movie id's in the dictionary that user 1 has rated

201
(array([   0,    2,    5,   43,   46,   62,   89,   97,  124,  130,  136,
        184,  190,  197,  201,  224,  257,  275,  291,  307,  314,  320,
        325,  367,  384,  398,  418,  436,  461,  476,  484,  485,  508,
        509,  510,  513,  520,  546,  551,  559,  592,  594,  615,  632,
        701,  705,  720,  723,  734,  767,  781,  782,  783,  786,  787,
        788,  789,  797,  801,  810,  815,  820,  828,  829,  831,  836,
        856,  863,  898,  899,  900,  907,  909,  911,  914,  915,  920,
        921,  923,  925,  927,  939,  955,  957,  964,  969,  974,  977,
        981,  990,  996, 1036, 1060, 1076, 1084, 1110, 1126, 1146, 1154,
       1171, 1181, 1183, 1190, 1218, 1220, 1224, 1235, 1261, 1298, 1319,
       1326, 1332, 1333, 1401, 1407, 1431, 1444, 1475, 1480, 1487, 1493,
       1503, 1505, 1516, 1517, 1522, 1526, 1543, 1553, 1556, 1557, 1559,
       1562, 1567, 1576, 1577, 1595, 1597, 1599, 1601, 1617, 1628, 1644,
       1674, 1687, 1691, 1704, 1734, 1743, 175

In [21]:
print(final_ratings.shape)
final_ratings = final_ratings[np.arange(1,final_ratings.shape[0]),:]
print(final_ratings.shape)

(611, 9742)
(610, 9742)
