In [2]:
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F

In [3]:
Rat = np.array([[4,5,6,7,8,9],[3,4,6,7,1,9],[2,5,6,8,9,10]],dtype=float).T
Rat = torch.from_numpy(Rat)
print(Rat) # 5,3
X = torch.randn((6,4),dtype = float,requires_grad = True)
theta = torch.randn((4,3),dtype =float, requires_grad = True)
preds = X @ theta 
loss_fn = F.mse_loss
weight_decay = 1e-5
regex = (torch.sum(torch.square(X)))*weight_decay
regtheta = (torch.sum(torch.square(theta)))*weight_decay
print(regex)
loss = loss_fn((X @ theta), Rat) + regex + regtheta
print("loss = ",loss) # use loss.item()
print(X,"\n",theta)


tensor([[ 4.,  3.,  2.],
        [ 5.,  4.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  8.],
        [ 8.,  1.,  9.],
        [ 9.,  9., 10.]], dtype=torch.float64)
tensor(0.0002, dtype=torch.float64, grad_fn=<MulBackward0>)
loss =  tensor(43.4737, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([[-0.8471, -0.0707,  0.2131,  1.9901],
        [-0.2563, -0.2863, -0.1902, -0.0922],
        [-0.2997,  1.2069, -0.7774,  0.7440],
        [ 0.0023, -0.4901,  1.1188,  0.4229],
        [-0.7414, -0.1921,  0.1089,  0.1770],
        [-0.0701,  0.5252, -1.8719, -1.3299]], dtype=torch.float64,
       requires_grad=True) 
 tensor([[ 1.3807, -0.5663,  0.3764],
        [-1.5232,  1.8752,  0.2846],
        [-0.2340, -1.2783, -1.2018],
        [-0.6453,  0.0967,  1.4855]], dtype=torch.float64, requires_grad=True)


In [4]:
batch_size = 5;
train_ds = TensorDataset(Rat)
#print(train_ds.tensors)
train_dl = DataLoader(train_ds,batch_size, shuffle = True)
for rat in train_dl:
  print(rat)
  break

[tensor([[ 4.,  3.,  2.],
        [ 8.,  1.,  9.],
        [ 7.,  7.,  8.],
        [ 6.,  6.,  6.],
        [ 9.,  9., 10.]], dtype=torch.float64)]


In [5]:
# opt = torch.optim.SGD((X,theta), lr = 1e-3, weight_decay = 1e-5)
# opt.step()
# num_epochs = 100

In [6]:
# for epoch in range(num_epochs):
        
#         # Train with batches of data
#         for rat in train_dl:
            
#             # 1. Generate predictions
#             preds = X @ theta
            
#             # 2. Calculate loss
            

#             print(loss)
            
#             # 3. Compute gradients
#             loss.backward()
            
#             # 4. Update parameters using gradients
#             opt.step()
            
#             # 5. Reset the gradients to zero
#             opt.zero_grad()

In [7]:


rat = Rat.clone().detach()
print(rat)

tensor([[ 4.,  3.,  2.],
        [ 5.,  4.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  8.],
        [ 8.,  1.,  9.],
        [ 9.,  9., 10.]], dtype=torch.float64)


In [8]:
# num_epochs = 1000
# learning_rate  = 1e-3;
# for i in range (num_epochs):
#   rat = X @ theta;
#   loss = loss_fn(rat, Rat);
#   loss.backward();
#   with torch.no_grad():
#     theta -= theta.grad*learning_rate
#     X -= X.grad*learning_rate
#     X.grad.zero_()
#     theta.grad.zero_()
#   #the variables in this system are X, theta and rat ( ratings ) 
  
# print(loss_fn((X @ theta),Rat), '\n')
# print("Predictions = \n", (X @ theta))
# print("Ratings =\n ",Rat)
# print(X)
# print(theta)



In [9]:

optimizer = torch.optim.SGD((X,theta), lr = 1e-3 , weight_decay = 1e-5)
for i in range (10000):
  for r in train_dl:
    loss = loss_fn(X @ theta, Rat)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()



In [ ]:
print(X @ theta)

tensor([[3.9021, 3.0137, 2.0840],
        [5.1253, 3.9825, 4.8924],
        [5.7633, 6.0331, 6.2032],
        [6.9087, 7.0127, 8.0784],
        [7.9722, 1.0039, 9.0238],
        [9.2095, 8.9707, 9.8200]], dtype=torch.float64, grad_fn=<MmBackward0>)


In [ ]:
print(Rat)

tensor([[ 4.,  3.,  2.],
        [ 5.,  4.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  8.],
        [ 8.,  1.,  9.],
        [ 9.,  9., 10.]], dtype=torch.float64)


In [ ]:
print(loss_fn((X @theta),Rat))

tensor(0.0131, dtype=torch.float64, grad_fn=<MseLossBackward0>)


In [ ]:
print(Rat)
print(theta)

tensor([[ 4.,  3.,  2.],
        [ 5.,  4.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  8.],
        [ 8.,  1.,  9.],
        [ 9.,  9., 10.]], dtype=torch.float64)
tensor([[ 0.2432,  0.9925,  0.2888],
        [ 0.3479,  0.7985,  0.2726],
        [-0.3281, -2.2023,  1.4194],
        [-0.6302, -1.3943,  1.2710]], dtype=torch.float64, requires_grad=True)
