In [2]:
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
%run dataloader.ipynb

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')
(100837, 4)
[[1.00000e+00 1.00000e+00 4.00000e+00]
 [1.00000e+00 3.00000e+00 4.00000e+00]
 [1.00000e+00 6.00000e+00 4.00000e+00]
 ...
 [6.10000e+02 1.68250e+05 5.00000e+00]
 [6.10000e+02 1.68252e+05 5.00000e+00]
 [6.10000e+02 1.70875e+05 3.00000e+00]]
9742
9742
<class 'dict'>
(9742,)
201
(array([   0,    2,    5,   43,   46,   62,   89, 

In [3]:
Rat = final_ratings
rat_bool = np.array(final_ratings.T > 0)
nums = np.sum(rat_bool,axis = 1,keepdims=True)
print(nums.shape)
nums_tensor = torch.from_numpy(nums)
print("shape of rat_bool = ",rat_bool.shape)
rat_bool_tensor = torch.from_numpy(rat_bool)
print("shape of Rat = ",Rat.shape)
num_users = Rat.shape[0]
print("num_users =",num_users)
num_movies = Rat.shape[1]
num_features = 10
rat_tensor = torch.from_numpy(Rat.T)
print("rat_tensor shape = ",rat_tensor.shape)
rat_tensor_masked = torch.mul(rat_tensor,rat_bool_tensor)
print("rat_tensor_masked shape = ",rat_tensor_masked.shape)
print("sum shape = ",torch.sum(rat_tensor_masked,dim=1,keepdim=True).shape)
rat_tensor_mean = rat_tensor_masked - (torch.div( (torch.sum(rat_tensor_masked,dim=1,keepdim=True)) ,nums_tensor))
print(rat_tensor_mean)
X = torch.randn((num_movies,10),dtype=float,requires_grad = True)
theta = torch.randn((num_features,num_users),dtype=float,requires_grad=True)
preds = X @ theta

print(rat_bool_tensor.shape)


(9742, 1)
shape of rat_bool =  (9742, 610)
shape of Rat =  (610, 9742)
num_users = 610
rat_tensor shape =  torch.Size([9742, 610])
rat_tensor_masked shape =  torch.Size([9742, 610])
sum shape =  torch.Size([9742, 1])
tensor([[ 0.0791, -3.9209, -3.9209,  ..., -1.4209, -0.9209,  1.0791],
        [-3.4318, -3.4318, -3.4318,  ..., -1.4318, -3.4318, -3.4318],
        [ 0.7404, -3.2596, -3.2596,  ..., -1.2596, -3.2596, -3.2596],
        ...,
        [-3.5000, -3.5000, -3.5000,  ..., -3.5000, -3.5000, -3.5000],
        [-3.5000, -3.5000, -3.5000,  ..., -3.5000, -3.5000, -3.5000],
        [-4.0000, -4.0000, -4.0000,  ..., -4.0000, -4.0000, -4.0000]],
       dtype=torch.float64)
torch.Size([9742, 610])


In [240]:

# # Rat = np.array([[4,5,6,7,8,9],[3,4,6,7,1,9],[2,5,6,8,9,10]],dtype=float).T
# Rat = torch.from_numpy(Rat)
# print(Rat) # 5,3
# X = torch.randn((6,4),dtype = float,requires_grad = True)
# theta = torch.randn((4,3),dtype =float, requires_grad = True)
# preds = X @ theta 
# loss_fn = F.mse_loss
# weight_decay = 1e-5
# regex = (torch.sum(torch.square(X)))*weight_decay
# regtheta = (torch.sum(torch.square(theta)))*weight_decay
# print(regex)
# loss = loss_fn((X @ theta), Rat) + regex + regtheta
# print("loss = ",loss) # use loss.item()
# print(X,"\n",theta)


In [4]:

train_ds = TensorDataset(rat_tensor_mean)
print(train_ds.tensors)
train_dl = DataLoader(train_ds,shuffle = False)
for rat in train_dl: 
    print(rat)
    break

(tensor([[ 0.0791, -3.9209, -3.9209,  ..., -1.4209, -0.9209,  1.0791],
        [-3.4318, -3.4318, -3.4318,  ..., -1.4318, -3.4318, -3.4318],
        [ 0.7404, -3.2596, -3.2596,  ..., -1.2596, -3.2596, -3.2596],
        ...,
        [-3.5000, -3.5000, -3.5000,  ..., -3.5000, -3.5000, -3.5000],
        [-3.5000, -3.5000, -3.5000,  ..., -3.5000, -3.5000, -3.5000],
        [-4.0000, -4.0000, -4.0000,  ..., -4.0000, -4.0000, -4.0000]],
       dtype=torch.float64),)
[tensor([[ 0.0791, -3.9209, -3.9209, -3.9209,  0.0791, -3.9209,  0.5791, -3.9209,
         -3.9209, -3.9209, -3.9209, -3.9209, -3.9209, -3.9209, -1.4209, -3.9209,
          0.5791, -0.4209,  0.0791, -3.9209, -0.4209, -3.9209, -3.9209, -3.9209,
         -3.9209, -3.9209, -0.9209, -3.9209, -3.9209, -3.9209,  1.0791, -0.9209,
         -0.9209, -3.9209, -3.9209, -3.9209, -3.9209, -3.9209, -3.9209,  1.0791,
         -3.9209, -3.9209,  1.0791, -0.9209,  0.0791,  1.0791, -3.9209, -3.9209,
         -3.9209, -0.9209, -3.9209, -3.9209, -3.

In [5]:
def model(X,theta):
    return X @ theta


In [6]:
def loss_fn(preds,targets,X,theta):
    weight_decay = 1e-5
    regex = (torch.sum(torch.square(X)))*weight_decay
    regtheta = (torch.sum(torch.square(theta)))*weight_decay
    return  (torch.square(torch.masked_select(rat_tensor_mean - (X @ theta),rat_bool_tensor))).sum() + regex + regtheta
    

In [7]:
preds = model(X,theta)
print(loss_fn(preds,rat_tensor_mean,X,theta))
print(torch.sum(rat_tensor_mean,dim = 1))
loss = (loss_fn(preds,rat_tensor_mean,X,theta))
loss.backward()
print(X)

tensor(1086297.0241, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([-1548.7674, -1715.9091, -1818.8654,  ..., -2131.5000, -2131.5000,
        -2436.0000], dtype=torch.float64)
tensor([[-0.2442, -1.9849, -0.1376,  ..., -0.2817,  0.4772, -0.1127],
        [-0.5512,  0.3451, -0.4545,  ...,  0.2815, -0.0739,  0.4858],
        [ 0.4964, -0.5047, -0.0205,  ...,  0.7145,  0.1853,  1.5187],
        ...,
        [-0.2635, -1.0343, -0.1766,  ...,  1.5549,  0.6744, -0.4574],
        [ 0.6654,  1.4743, -0.0398,  ..., -0.9085, -2.5979, -0.9922],
        [ 0.7527, -0.4602, -0.4651,  ...,  0.2984, -1.5107, -2.3271]],
       dtype=torch.float64, requires_grad=True)


In [18]:
epochs = 100

for i in range(100):
    # Iterate through training dataloader
    #print(X)
   
    # Generate Prediction
    preds = model(X,theta)
    loss = loss_fn(preds,rat_tensor_mean,X,theta)
    loss.backward()

    with torch.no_grad():
        X -= X.grad *1e-7
        theta -= theta.grad * 1e-7
        # Set the gradients to zero
        X.grad.zero_()
        theta.grad.zero_()

    print(f"Epoch {i}/{epochs}: Loss: {loss}")

print("The loss function decreases but the loss is too high and will take too much time to train ! , will overcome this later vy using Adagrad optimizer ")

Epoch 0/100: Loss: 1085604.7561712437
Epoch 1/100: Loss: 1085603.6207766375
Epoch 2/100: Loss: 1085602.486581551
Epoch 3/100: Loss: 1085601.3535859727
Epoch 4/100: Loss: 1085600.221789892
Epoch 5/100: Loss: 1085599.0911932974
Epoch 6/100: Loss: 1085597.961796177
Epoch 7/100: Loss: 1085596.8335985206
Epoch 8/100: Loss: 1085595.7066003156
Epoch 9/100: Loss: 1085594.580801551
Epoch 10/100: Loss: 1085593.4562022164
Epoch 11/100: Loss: 1085592.3328022994
Epoch 12/100: Loss: 1085591.2106017892
Epoch 13/100: Loss: 1085590.0896006743
Epoch 14/100: Loss: 1085588.9697989437
Epoch 15/100: Loss: 1085587.8511965862
Epoch 16/100: Loss: 1085586.7337935898
Epoch 17/100: Loss: 1085585.617589944
Epoch 18/100: Loss: 1085584.5025856374
Epoch 19/100: Loss: 1085583.3887806586
Epoch 20/100: Loss: 1085582.276174996
Epoch 21/100: Loss: 1085581.164768639
Epoch 22/100: Loss: 1085580.054561576
Epoch 23/100: Loss: 1085578.9455537961
Epoch 24/100: Loss: 1085577.8377452877
Epoch 25/100: Loss: 1085576.7311360394
Epoc

In [10]:
print(X @ theta)

tensor([[ 2.5680e+00,  3.3531e+00, -1.1466e+00,  ...,  4.1232e-01,
          3.3527e+00, -5.3684e+00],
        [-6.6235e-01,  3.4675e-01,  2.1031e-01,  ..., -1.4643e-01,
          2.9233e+00,  3.4158e+00],
        [ 9.2118e-01,  1.3144e+00, -9.3630e-01,  ..., -6.1703e+00,
          3.4750e+00, -2.1345e+00],
        ...,
        [ 1.6614e+00,  2.8331e+00, -2.1030e+00,  ..., -1.1588e-01,
          2.1031e+00, -3.3417e+00],
        [ 5.2432e-01, -4.8543e+00,  1.8346e+00,  ...,  5.6003e+00,
         -4.2558e+00,  2.7036e+00],
        [ 1.7781e+00,  1.2427e-03, -9.4708e-01,  ...,  6.2157e+00,
          2.0036e+00, -2.8159e+00]], dtype=torch.float64,
       grad_fn=<MmBackward0>)


In [11]:
print(Rat)

[[4.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 2.  2.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]


In [15]:
print(loss_fn((X @theta),Rat,X,theta))

tensor(1085604.7562, dtype=torch.float64, grad_fn=<AddBackward0>)


In [13]:
print(Rat)
print(theta)

[[4.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 2.  2.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]
tensor([[-0.7944, -0.6532,  0.3844,  ..., -0.7768, -1.1721, -1.2436],
        [-1.3465, -1.9497,  0.6739,  ...,  0.4272, -0.2464,  1.9913],
        [ 1.5645, -0.3043, -1.0690,  ..., -2.1173,  0.1139,  0.0481],
        ...,
        [ 0.0800, -0.2370, -0.8331,  ...,  0.0671,  0.8576,  0.5397],
        [-0.5923,  0.6851,  0.3072,  ..., -0.3841,  0.2433, -0.3813],
        [-0.0268, -0.1760,  0.0970,  ..., -2.6719,  0.6093, -0.1754]],
       dtype=torch.float64, requires_grad=True)
